### ISSUE TITLE
Working on Safari but not ob Chrome

### ISSUE THREAD

**Issue by rayburnside** [jaredatch/Shared-Counts#100]
## Current Behavior

On Chrome I have no links to Facebook or twitter

## Expected Behavior

Below all posts on Safari I have a Facebook and a Twitter link. Not on Chrome

## Steps to Reproduce (for bugs)

Safari – works fine. Chrome no links, no buttons..
http://blog.timeofpandemic.co.uk/2020/06/11/lockdown-the-rolling-stones-now/

1.
2.
3.
4.

**Comment by billerickson** [comment]
I see the social buttons on Chrome:

![screenshot](https://p198.p4.n0.cdn.getcloudapp.com/items/4guj7vyO/Image%202020-06-11%20at%201.51.08%20PM.png?v=ebcfeb242518db45ead98b2f64ed3825)
