### ISSUE TITLE
Shared Counts plugin is not compatible with AMP as counts are not shown

### ISSUE THREAD

**Issue by ajaycc17** [jaredatch/Shared-Counts#102]
## Plugin version
The Latest Version on 9th September 2020

## Current Behavior
The plugin is working fine on normal pages but on AMP pages the counts are not registered.

## Possible Solution
It should comply with AMP official plugin and should either fix that issue or add a plain text option in the place of counts for AMP pages.

**Comment by billerickson** [comment]
Can you please describe your issue? 

Shared Counts is compatible with AMP and counts are shown. You can see it working [on my blog](https://www.billerickson.net/innerblocks-with-acf-blocks/?amp)

![screenshot](https://p198.p4.n0.cdn.getcloudapp.com/items/5zuGRd0B/Image%202020-09-09%20at%2010.00.05%20AM.png?source=viewer&v=20950c10c0d7f923d291499dfee28dad)

**Comment by ajaycc17** [comment]
It is working on regular pages but on AMP pages the "Counts are not shown". Can I replace the count section with plain text?

**Comment by billerickson** [comment]
Can you provide a link to an AMP page where it doesn't work? Are you sure it isn't a caching issue?

The count section **is** plain text already. It doesn't use JavaScript or anything dynamic to render.
