### ISSUE TITLE
AMP share counts shown 0 always

### ISSUE THREAD

**Issue by ajaycc17** [jaredatch/Shared-Counts#103]
The counts are always shown "0 shares" on an AMP page. How to replace the counts' section with plain text?
![Screenshot (18)](https://user-images.githubusercontent.com/40439694/92617346-d0524180-f2dc-11ea-8bfa-ca20fecff11e.png)

**Comment by jaredatch** [comment]
Please do not create multiple issues.

If you have more details provide them in the original issues and we will assist where possible :)

https://github.com/jaredatch/Shared-Counts/issues/102
