### ISSUE TITLE
Text print out of count showing up under the buttons

### ISSUE THREAD

**Issue by gbolewitz** [jaredatch/Shared-Counts#109]
Facebook0Tweet0Pin0Email0Print0…

This is an example of a printout from the plugin that is showing up under the buttons.  It only shows up when the plugin renders for a "related post" section under a primary post.  anyway to remove this text printout?  check joyforher.com and click any post and scroll down to related post section to view.

![image](https://user-images.githubusercontent.com/77295885/104224428-f9ade600-5412-11eb-8fad-68b0cc6a01cf.png)

**Comment by billerickson** [comment]
Sorry for the delay. I'm not able to find the issue on your site right now. It looks like you're outputting two sets of share buttons (one with styling, one without).
