### ISSUE TITLE
custom email modal styles

### ISSUE THREAD

**Issue by lilianammmatos** [jaredatch/Shared-Counts#110]
Hi there! I was wondering if it was kosher to target the email modal classes to add some custom styling to better match the theme on my WP site. I didn't see any options or filters that support this in any of the documentation. Thanks for your time!

## Plugin version
`1.3.0`

**Comment by billerickson** [comment]
Yes, you can definitely style the modal. We tried to keep the default styling fairly basic so it can be updated in the theme.

You can also disable the CSS and JS in Shared Counts using:

```
// Disable CSS and JS.
add_filter( 'shared_counts_load_css', '__return_false' );
add_filter( 'shared_counts_load_js', '__return_false' );
```

That's what I do in most of the custom themes I build.
