### ISSUE TITLE
Dynamic increase by type

### ISSUE THREAD

**Issue by egbamddeveloper** [jaredatch/Shared-Counts#111]
Hello, 

It's a perfect app, thanks very much.

I want to increase data dynamic by code or api, how?
I see that can i get data by api, but how can i increase it?

Thanks very much
Ahmad

**Comment by billerickson** [comment]
There are a few ways you could update it. 

The simplest would be directly updating the post_meta values on the specific posts you'd like changed. Look for the `shared_counts` and `shared_counts_total` meta keys.

You can also use the [shared_counts_query_api](https://github.com/jaredatch/Shared-Counts/blob/develop/includes/class-shared-counts-core.php#L422) hook to add your own code for retrieving or determining the share count when the counts are updated.

**Comment by egbamddeveloper** [comment]
Very helpful, Thanks 👍
