### ISSUE TITLE
SharedCount integration issues

### ISSUE THREAD

**Issue by annabellegauberti** [jaredatch/Shared-Counts#115]
Login

info@crefovi.com

LChange
Domain

api.sharedcount.com

Hi ShareCount,

I have been using your services for a couple of years now, on our law firm's main English language website, https://crefovi.com, and on our French language website, https://crefovi.fr.

https://crefovi.com/wp-content/uploads/2018/07/CREFOVI-logo_200_RGB_SCREEN.jpg

Crefovi, London law firm expert in advising the creative industries

Crefovi, law firm for the creative industries, which offices are located in London and Paris, advises the luxury & fashion, music, film and entertainment, art as well as high tech sectors, among other creative industries.. We assist our clients, who all work in creative fields, to find the best solutions to their various legal issues, relating to business law, on matters which are either ...

crefovi.com

https://crefovi.fr/wp-content/uploads/2012/06/CREFOVI-logo_200_RGB_SCREEN.jpg

Crefovi, cabinet d'avocats expert en conseil aux industries créatives

Crefovi, le cabinet d’avocats pour les industries créatives, dont les bureaux sont basés à Londres et Paris, conseille les secteurs du luxe & de la mode, de la musique, du cinéma et des arts du spectacle, de l’art et des hautes technologies, parmi d’autres industries créatives.. Nous assistons nos clients, qui travaillent tous dans des domaines créatifs, à trouver les meilleures ...

crefovi.fr

However, I have noticed that there are a few technical problems, as follows.

Would you please review those issues and revert back to me please, by return of emial, with constructive and clear answers as to how to address these technical issues?

1/ Twitter counts

As recommended in your article https://sharedcountsplugin.com/2019/05/13/shared-counts-version-1-3/, I have set up a https://twitcount.com/ account, which is now linked with our Twitter account, @Crefovi

However, I note that the integration between your plugin Shared Count and twitcount is not optimal.

In particular, all my articles or podcasts on crefovi.com and crefovi.fr show as not having been shared on twitter, while I know that they have been since I always share our articles to twitter, on @crefovi when I publish them, by clicking on the "Tweet" button at the top/bottom of the post's or podcast's page.

Therefore, would you please clarify how I may configure your Shared Counts plugin, with our account www.twitcount.com, in order to ensure that we may see the number of times the content has been shared on tweeter, from the SharedCount plugin settings?

2/ Linkedin sharing counts

I note that there are no "linkedin sharing counts", on the SharedCount plugin stats, on both our websites crefovi.com and crefovi.fr

Why is that?

Is this something that may be remedied, so that I may see how many people shared the content (posts and podcasts) on linkedin, please?

3/ Social interaction tracking on Google analytics

Despite what is set out on your article, here https://sharedcountsplugin.com/2019/05/13/shared-counts-version-1-3/, I note that your social media plugin ShareCound does NOT appear at all in our Google Analytics accounts for Crefovi.com and crefovi.fr.

What is the solution, please, to ensure that your social media plugin ShareCount is tracked by our Google Analytics accounts?

Thank you in advance for your prompt and clear reply and best ergards,

https://sharedcountsplugin.com/wp-content/uploads/2019/03/sharing.jpg

Shared Counts 1.3: Twitter counts, Google Analytics integration, and more - Shared Counts

We just released version 1.3 of Shared Counts, which includes some great new features and improvements. Twitter counts using TwitCount Our previous provider of Twitter share counts shut down, so we’ve added support for the new leader in Twitter counts, TwitCount. Sign up for free on the TwitCount website, then on your website go to […]

sharedcountsplugin.com

https://twitcount.com/images/ogimage-min.jpg

TwitCount - Twitter Share Counts Alternative

A free fix for Twitter's decision to deactivate share counts

www.twitcount.com

https://twitcount.com/images/ogimage-min.jpg

TwitCount - Twitter Share Counts Alternative

Twitter said the move was due to technical reasons. They explained that the decision to discontinue the feature was meant to speed up improvements in its technology and that the API the publishers were using to pull in the page shares count was an unofficial hack.

twitcount.com

https://sharedcountsplugin.com/wp-content/uploads/2019/03/sharing.jpg

Shared Counts 1.3: Twitter counts, Google Analytics integration, and more - Shared Counts

We just released version 1.3 of Shared Counts, which includes some great new features and improvements. Twitter counts using TwitCount Our previous provider of Twitter share counts shut down, so we’ve added support for the new leader in Twitter counts, TwitCount. Sign up for free on the TwitCount website, then on your website go to […]

sharedcountsplugin.com

**Comment by annabellegauberti** [comment]
OI, GITHUB, CAN I GET A MOVE ON???


I EMAILED YOU ON 15 MAY 2021 ABOVE AND YOU PEOPLE NEVER REPLIED TO MY SUPPORT MESSAGE BELOW.

CAN I GET SOME TRACTION???


Login

info@crefovi.com

LChange
Domain

api.sharedcount.com

Hi ShareCount,

I have been using your services for a couple of years now, on our law firm's main English language website, https://crefovi.com, and on our French language website, https://crefovi.fr.

https://crefovi.com/wp-content/uploads/2018/07/CREFOVI-logo_200_RGB_SCREEN.jpg

Crefovi, London law firm expert in advising the creative industries

Crefovi, law firm for the creative industries, which offices are located in London and Paris, advises the luxury & fashion, music, film and entertainment, art as well as high tech sectors, among other creative industries.. We assist our clients, who all work in creative fields, to find the best solutions to their various legal issues, relating to business law, on matters which are either ...

crefovi.com

https://crefovi.fr/wp-content/uploads/2012/06/CREFOVI-logo_200_RGB_SCREEN.jpg

Crefovi, cabinet d'avocats expert en conseil aux industries créatives

Crefovi, le cabinet d’avocats pour les industries créatives, dont les bureaux sont basés à Londres et Paris, conseille les secteurs du luxe & de la mode, de la musique, du cinéma et des arts du spectacle, de l’art et des hautes technologies, parmi d’autres industries créatives.. Nous assistons nos clients, qui travaillent tous dans des domaines créatifs, à trouver les meilleures ...

crefovi.fr

However, I have noticed that there are a few technical problems, as follows.

Would you please review those issues and revert back to me please, by return of emial, with constructive and clear answers as to how to address these technical issues?

1/ Twitter counts

As recommended in your article https://sharedcountsplugin.com/2019/05/13/shared-counts-version-1-3/, I have set up a https://twitcount.com/ account, which is now linked with our Twitter account, @Crefovi

However, I note that the integration between your plugin Shared Count and twitcount is not optimal.

In particular, all my articles or podcasts on crefovi.com and crefovi.fr show as not having been shared on twitter, while I know that they have been since I always share our articles to twitter, on @crefovi when I publish them, by clicking on the "Tweet" button at the top/bottom of the post's or podcast's page.

Therefore, would you please clarify how I may configure your Shared Counts plugin, with our account www.twitcount.com, in order to ensure that we may see the number of times the content has been shared on tweeter, from the SharedCount plugin settings?

2/ Linkedin sharing counts

I note that there are no "linkedin sharing counts", on the SharedCount plugin stats, on both our websites crefovi.com and crefovi.fr

Why is that?

Is this something that may be remedied, so that I may see how many people shared the content (posts and podcasts) on linkedin, please?

3/ Social interaction tracking on Google analytics

Despite what is set out on your article, here https://sharedcountsplugin.com/2019/05/13/shared-counts-version-1-3/, I note that your social media plugin ShareCound does NOT appear at all in our Google Analytics accounts for Crefovi.com and crefovi.fr.

What is the solution, please, to ensure that your social media plugin ShareCount is tracked by our Google Analytics accounts?

Thank you in advance for your prompt and clear reply and best ergards,

https://sharedcountsplugin.com/wp-content/uploads/2019/03/sharing.jpg

Shared Counts 1.3: Twitter counts, Google Analytics integration, and more - Shared Counts

We just released version 1.3 of Shared Counts, which includes some great new features and improvements. Twitter counts using TwitCount Our previous provider of Twitter share counts shut down, so we’ve added support for the new leader in Twitter counts, TwitCount. Sign up for free on the TwitCount website, then on your website go to […]

sharedcountsplugin.com

https://twitcount.com/images/ogimage-min.jpg

TwitCount - Twitter Share Counts Alternative

A free fix for Twitter's decision to deactivate share counts

www.twitcount.com

https://twitcount.com/images/ogimage-min.jpg

TwitCount - Twitter Share Counts Alternative

Twitter said the move was due to technical reasons. They explained that the decision to discontinue the feature was meant to speed up improvements in its technology and that the API the publishers were using to pull in the page shares count was an unofficial hack.

twitcount.com

https://sharedcountsplugin.com/wp-content/uploads/2019/03/sharing.jpg

Shared Counts 1.3: Twitter counts, Google Analytics integration, and more - Shared Counts

We just released version 1.3 of Shared Counts, which includes some great new features and improvements. Twitter counts using TwitCount Our previous provider of Twitter share counts shut down, so we’ve added support for the new leader in Twitter counts, TwitCount. Sign up for free on the TwitCount website, then on your website go to […]

sharedcountsplugin.com

**Comment by billerickson** [comment]
The TwitCount service only starts gathering twitter share data once you connect to it. It does not gather previously shared data unfortunately.

LinkedIn does not have an API for retrieving the number of shares an article has received, so there's no way for us to gather that data.

Our social interactions tracking integrates with the default Google Analytics code (`ga`) and the Monster Insights plugin (`__gaTracker`). If you are using a different plugin or tool for your GA code, you'll need to add your own social interaction tracking JS. [You can use this as a guide](https://github.com/jaredatch/Shared-Counts/blob/develop/assets/js/shared-counts.js#L35-L41).
