### ISSUE TITLE
Not able to see shared counts plugin buttons on a wordpress.org website

### ISSUE THREAD

**Issue by nehamehta123** [jaredatch/Shared-Counts#116]
## Current Behavior
No button showing
Should I add the google site verification key for my site, is it necessary

## Possible Solution
<!-

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by nehamehta123** [comment]
Should I delete the previous share buttons for facebook, twitter and google plus included on my posts. is it necessary to add the google site verification key.

**Comment by billerickson** [comment]
Go to Settings > Shared Counts to configure which buttons to show and where to automatically display them (above content and/or below content). 

No, a Google Site Verification key is not needed.
