### ISSUE TITLE
Facebook count isn't showing on the metabox

### ISSUE THREAD

**Issue by dhanendran** [jaredatch/Shared-Counts#117]
## Plugin version
1.3.0

## Current Behaviour
Facebook count is always 0 in metabox

## Expected Behaviour
In metabox, Facebook count should show the count from FB

## Possible Solution
We need to pass the `fields=engagement` query param to https://graph.facebook.com/. At the moment plugin is passing only the id and token, with this param FB is returning the same id which we passed. When I add the `fields=engagement` to the URL, I'm getting reaction_count, share_count, comment_count.

## Steps to Reproduce (for bugs)
https://graph.facebook.com/?id=https%3A%2F%2Fbreakingdefense.com%2F2021%2F04%2Fwhy-putin-threatens-ukraine%2F&access_token={FB_TOKEN}

https://graph.facebook.com/?id=https%3A%2F%2Fbreakingdefense.com%2F2021%2F04%2Fwhy-putin-threatens-ukraine%2F&access_token={FB_TOKEN}&fields=engagement

## Screenshots (if appropriate)
Current behaviour
![Screenshot 2021-06-08 at 6 47 08 PM](https://user-images.githubusercontent.com/6737105/121191815-f3207f00-c889-11eb-801f-6f1e07523a28.png)
Expected behaviour
![Screenshot 2021-06-08 at 6 47 02 PM](https://user-images.githubusercontent.com/6737105/121191824-f74c9c80-c889-11eb-8959-99a7e2173dca.png)

**Comment by billerickson** [comment]
This was [fixed here](https://github.com/jaredatch/Shared-Counts/commit/9a51811c236698e084289dc9b72ff0cb17f1c0ae) and will be in the next release (1.4.0)
