### ISSUE TITLE
Pinterest Sharing Image not showing

### ISSUE THREAD

**Issue by BraverBolderLiving** [jaredatch/Shared-Counts#118]
## Plugin version
Shared Counts - Pinterest Image Version 1.4.0
## Current Behavior

I installed and activated the plugin for Shared Counts - Pinterest Sharing image, when I click on the plus sign to insert a widget I don't see the 'Pinterest Sharing Image' option.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/85579581/121235658-b4270500-c85a-11eb-96a3-5637ccc5ddb2.png)
![image](https://user-images.githubusercontent.com/85579581/121235743-cb65f280-c85a-11eb-9715-f641b1d51c37.png)
![image](https://user-images.githubusercontent.com/85579581/121235773-d6b91e00-c85a-11eb-9f98-c900151d684a.png)
![image](https://user-images.githubusercontent.com/85579581/121235814-e20c4980-c85a-11eb-830d-4efd7ab7e446.png)
![image](https://user-images.githubusercontent.com/85579581/121235876-f2bcbf80-c85a-11eb-969b-45ea11833556.png)
![image](https://user-images.githubusercontent.com/85579581/121235953-05cf8f80-c85b-11eb-97d0-9d4453b29819.png)
![image](https://user-images.githubusercontent.com/85579581/121235985-0ff18e00-c85b-11eb-9a94-91c1753a43f7.png)
![image](https://user-images.githubusercontent.com/85579581/121236025-1da71380-c85b-11eb-874f-0529ae3ac92a.png)
![image](https://user-images.githubusercontent.com/85579581/121236062-2992d580-c85b-11eb-9a1c-2e6b6761b0af.png)
![image](https://user-images.githubusercontent.com/85579581/121236096-344d6a80-c85b-11eb-9d28-3e2f523f635b.png)

**Comment by billerickson** [comment]
The Pinterest Sharing Image is not a block. It adds a metabox to the right column of the screen for specifying the image: 

![screenshot](https://p198.p4.n0.cdn.getcloudapp.com/items/yAurv08E/4f59ec74-2ec3-414f-9d4a-f88b7e059558.png?source=viewer&v=53efdba68be56ede1fd080492d5315d8)

**Comment by BraverBolderLiving** [comment]
Thank you for the help and quick response.  I was able to find the right column metabox now.

 

Is it possible to add more than one Pinterest image to a blog post or is it limited to just one?

**Comment by billerickson** [comment]
It's limited to just one. You can of course add as many images as you like to the post content and those will all be options if someone uses the Pinterest browser extension, but only one image can be pinned when they click the Pinterest button in Shared Counts.
