### ISSUE TITLE
PHP Deprecated:  Required parameter $post_id follows optional parameter $group

### ISSUE THREAD

**Issue by mwks-jg** [jaredatch/Shared-Counts#123]
## Plugin version
1.4.0

## Current Behavior

Running the plugin locally with PHP 8.0.22 I see the below deprecated notice in WP debug log.

PHP Deprecated:  Required parameter $post_id follows optional parameter $group in /wp-content/plugins/shared-counts/includes/class-shared-counts-admin.php on line 979

**Comment by cdils** [comment]
Confirming I also see this in v.1.4.0 running PHP 8.0.

![image](https://user-images.githubusercontent.com/3099408/206224510-1fa31073-b58d-4f07-a518-c61d0e1f807d.png)
