### ISSUE TITLE
Titles of posts get squashed to 6 character length in Posts Dashboard when plugin installed

### ISSUE THREAD

**Issue by GordonGit** [jaredatch/Shared-Counts#128]
Plugin version 1.4.1

Current Behavior - when plugin is activated, titles of posts are limited to 6 characters per line when viewed in Wordpress Dashboard in the Posts tab. This makes it difficult to read and navigate posts.

Steps to Reproduce (for bugs) - activate the plugin. I'm using WordPress 6.2 with Astra theme version 4.1.2. The following other plugins are installed: 
- Contact Form 7, version 5.7.5.1
- Elementor, version 3.12.1
- Hostinger, version 1.2.0
- Hot Random Image, version 1.8
- LiteSpeed Cache, version 5.3.3
- Subscribe Forms, version 1.5.8
- WP Statistics, version 14.0.2
- Yoast SEO, version 20.4

Screenshot - 
![shared count bug 2023-04-09](https://user-images.githubusercontent.com/7726900/230769269-2944aa11-d6cd-411d-ab01-d536f34d6d9c.jpg)

**Comment by billerickson** [comment]
If you click "Screen Options" in the top right, you can control which columns are visible. 

In your screenshot, the columns for Yoast SEO and WP Statistics are taking up a significantly larger amount of the screen than Shared Counts.
