### ISSUE TITLE
Shared link invalid href attribute

### ISSUE THREAD

**Issue by matsonc** [jaredatch/Shared-Counts#130]
The shared link can have an invalid href attribute because the url is escaped using esc_attr instead of esc_url

## Possible Solution
In wp-content\plugins\shared-counts\includes\class-shared-counts-front.php on line 685
replace esc_attr with esc_url

```
$elements['wrap_open']  = sprintf(
  '<a href="%s"%s%s%s class="%s"%s>',
  esc_attr( $link['link'] ),
  $attr_title,
  $target,
  $rel,
  $css_classes,
  $data
 );
```

```
$elements['wrap_open']  = sprintf(
  '<a href="%s"%s%s%s class="%s"%s>',
  esc_url( $link['link'] ),
  $attr_title,
  $target,
  $rel,
  $css_classes,
  $data
 );
```

**Comment by billerickson** [comment]
@matsonc I think I figured out why we were using `esc_attr()` . With this update, the print button no longer works. 

See #133
