### ISSUE TITLE
Branding Assets

### ISSUE THREAD

**Issue by billerickson** [jaredatch/Shared-Counts#16]
Now that we're releasing this on WordPress.org, we should prepare some branding assets to go along with the plugin.

1. Some type of logo / icon
2. Banner
3. Plugin Icon

### Banner 
- Normal Banner: banner-772x250.(jpg|png)
- High-DPI (Retina): banner-1544x500.(jpg|png)

### Plugin Icon
- Normal: icon-128x128.(png|jpg)
- High-DPI (Retina): icon-256x256.(png|jpg)
- SVG: icon.svg

### Screenshots
- screenshot-1.(png|jpg)
- screenshot-2.(png|jpg)

I'll do this right before we launch so they are up-to-date.

## Examples
- [Akismet](https://wordpress.org/plugins/akismet/)
- [Jetpack](https://wordpress.org/plugins/jetpack/)
- [WP Super Cache](https://wordpress.org/plugins/wp-super-cache/)
- [WPForms](https://wordpress.org/plugins/wpforms-lite/)
- [Display Posts Shortcode](https://wordpress.org/plugins/display-posts-shortcode/)

**Comment by jaredatch** [comment]
The RTL banners are deprecated and no longer needed because in the new plugin repo design the text is no longer overlapping the header image :)

**Comment by billerickson** [comment]
Cool! Updated the post above. They really need to update the [plugin docs](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/)

**Comment by jaredatch** [comment]
Here's another few good banners
https://ps.w.org/google-analytics-for-wordpress/assets/banner-1544x500.png?rev=1598927
https://ps.w.org/woocommerce/assets/banner-1544x500.png?rev=1629184

**Comment by billerickson** [comment]
What should we include in our banner? Just different styles of buttons?

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/243F1W3y2Z0j3p0i000E/banner.jpg?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=e0e6f1cd)

Or a screenshot of a client site using the buttons: 

![banner-screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/1w251y1o0s2t3D2U2V00/banner-screenshot.jpg?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=59bcc911)

**Comment by jaredatch** [comment]
Maybe we can do something like SW?

https://ps.w.org/social-warfare/assets/banner-1544x500.jpg?rev=1466435

Basically generic page content and highlight/call out the sharing? The other options just look a bit "off" to me, can't put my finger on it lol.

**Comment by billerickson** [comment]
Yeah I like that.

I agree, the mockups I did didn't look right, but I didn't know what to put there.

**Comment by billerickson** [comment]
Final banner:

![banner](https://d3vv6lp55qjaqc.cloudfront.net/items/0o2o3G3p2A3c3M3p2m2M/Banner.jpg?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=b70c473c)
