### ISSUE TITLE
Yummly share count support

### ISSUE THREAD

**Issue by jaredatch** [jaredatch/Shared-Counts#24]
Yummly is _very_ popular with Foodies.

After some research their API to get share count is super simple. See below, this was ripped from another script.

```php
	/**
	 * Get yummly share count.
	 *
	 * @param string $url_current_page the current page url.
	 *
	 * @return int|string
	 */
	public function get_yummly_share_count( $url_current_page ) {
		// Get results from yummly and return the number of shares.
		$result = wp_safe_remote_get( 'http://www.yummly.com/services/yum-count?url=' . $url_current_page, array(
			'timeout' => 6,
		) );

		// Check there was an error.
		if ( is_wp_error( $result ) ) {
			return 0;
		}

		// Decode data.
		$array = json_decode( $result['body'], true );
		$count = isset( $array['count'] ) ? $array['count'] : '0';

		// Return.
		return $count;
	}
```

IMO, this should be considered for core. It wouldn't add hardly any code and if they were not using Yummly, then there is no processing overhead. But for pretty much anyone with a food related site, it would be a massive value. Also an extra differentiator between us and other solutions out there.

Lastly, with other services dropping share counts, it would be good to have another option that could contribute to the share count total.

Thoughts @billerickson ?

**Comment by jaredatch** [comment]
Also wanted to add, that I'll be adding this for a client, so I'm already going to be doing the work. Just figured it would make the most sense to include it in core.

**Comment by billerickson** [comment]
I like it! Let's add it for the next release

**Comment by jaredatch** [comment]
This is in develop. All that remains is Yummly style adjustments in the themes.

**Comment by jaredatch** [comment]
Closing, in 1.1.0 💥
