### ISSUE TITLE
Shared Count Stats

### ISSUE THREAD

**Issue by jaredatch** [jaredatch/Shared-Counts#26]
This is an idea/pitch.

Currently we have the Most Shared Content admin dashboard widget. My clients, one in specific that I upgraded to SC, are finding that widget _**immensely**_ useful. Because realistically, other than widget, there is no easy way to find these stats. So that widget is used to look at the popular content (eg what has really taken off on Pinterest, for example), but also then they can focus on promoting the popular content more. For example, they can tell X post, from a few years ago is wildly popular (which means readers have taken a liking to it), and focus on re-sharing it on social media.

My idea is to add tabs to the Shared Counts settings page. The primary and default tab would be "Settings" and would contain all the information you see now. 

In addition to that we would add a "Stats" tab. This tab would have table (styled like the posts edit screen table probably) of all the Shared Counts stats.  We'd query all posts (posts_per_page -1) and sort by highest share count (like the dashboard widget). I'm thinking in the table the columns would be Post Name, Total, then followed by Facebook, Twitter, etc. We can use jQuery to make the table searchable (eg find me post title that contains Chocolate Cookies) and sortable (sort by Pinterest count, or total count, etc).

The dashboard widget would then show the 20 top posts and under that have a link "See more stats", which links directly to the Stats tab.

I think this would be a killer feature, be pretty easy to implement, and wouldn't add much overhead since it is just presenting stats we already have collecting (past adding a jQuery library or two for the searching/sorting).

Thoughts @billerickson ?

**Comment by billerickson** [comment]
I like it.

A simpler option would be to add a "Share Count" column to the backend post listing for all supported post types, then make it sortable. The "See More Stats" would link to `admin_url( 'edit.php?orderby=share_count&order=desc' )`.

I don't think the specific service is as important on this listing than the total count. For a food blog, the majority of the shares will be Pinterest and Yummly on all the posts. Another site might see 90% of shares from FB.  While the numbers will be different, the rough percentage breakdown will be the same for most posts. Also, how do we decide which of the many services we support to feature in the columns? 

If we do go with our own, don't query for `'posts_per_page' => -1`. Grab at most 100 posts and sort by share count. We can then paginate the results. Many of the sites we've set this up on have a ton of posts and querying for all posts would cause big performance problems.

**Comment by billerickson** [comment]
See the [post-listing-column](https://github.com/jaredatch/Shared-Counts/tree/post-listing-column) branch.

Here's what it looks like when I sort by share count:

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/0g3c3M1t110P3T1B3Z0t/Screen%20Shot%202018-03-17%20at%208.44.18%20AM.png?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=a1bd0661)

And I can use the search feature to find specific posts:

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/2M043g0M3w3i2S2C1i45/Screen%20Shot%202018-03-17%20at%208.45.29%20AM.png?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=4db5be41)

**Comment by jaredatch** [comment]
Definitely think that is better. To keep things tidy in the table, another few options we may consider: 

- Display shorthand count, eg 3.7k (can click through to see exact #)
- Use dash icon instead of Shared Count in table heading (https://developer.wordpress.org/resource/dashicons/#share)
- set a width via inline admin css for that table column to keep it narrow

That would get the column looking more like the comment count column.

**Comment by billerickson** [comment]
Yep, I was thinking the same thing.

Is there a way to use our icon instead of the generic share icon?

**Comment by jaredatch** [comment]
Oh yeah, we could just use an SVG I guess 😁

**Comment by billerickson** [comment]
New style:

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/1z3Y2w1q0k2Q1g0R2e0r/Screen%20Shot%202018-03-17%20at%209.18.17%20AM.png?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=2f873749)

**Comment by jaredatch** [comment]
Looks perfect to me 😎

**Comment by billerickson** [comment]
I have it set to round to 2 significant digits, but rounding only kicks in at >1000 shares and I don't have anything that popular, haha. 

Awesome, I'll merge into develop.
