### ISSUE TITLE
Admin bar share counts and refresh

### ISSUE THREAD

**Issue by jaredatch** [jaredatch/Shared-Counts#32]
Right now if you want to refresh the share counts, you need to go into the edit post screen, locate the Shared Counts metabox, and click refresh.

What could be helpful is having an admin bar item.

<img width="630" alt="screen shot 2018-04-23 at 3 23 03 pm" src="https://user-images.githubusercontent.com/630686/39151275-5b37f226-470a-11e8-977e-65dcfe5c994d.png">

Basically for post types that are supported:

- Show the share count, if stored.
- Show when cache was last updated.
- Clicking the menu item will go to `?sc_refresh=1` - we'll add a hook that looks for that checks for appropriate cap (I think `manage_options` by default, can be filterable) - if those pass trigger refresh.

Thoughts?

**Comment by billerickson** [comment]
I like it!
