### ISSUE TITLE
Pinterest button taken over by pinit.js

### ISSUE THREAD

**Issue by billerickson** [jaredatch/Shared-Counts#34]
If your site includes the [pinit.js code](https://gist.github.com/billerickson/acfcbeee427993fba3d2e14fcc0e0df5) from Pinterest, the Pinterest button is converted into a "Save" button:

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/0L3j3C0P2e110A3w0w2q/Screen%20Shot%202018-05-03%20at%203.09.39%20PM.png?X-CloudApp-Visitor-Id=095a13821a9a7633d8999bdb4bf2b94a&v=96db4958)

I believe this has to do with the URL of the link. In [this post](https://wordpress.org/support/topic/custom-pinterest-share-button-and-issues-with-pinit-js/) it's recommended to use `//pinterest.com/pin/create/%20button?url` for custom share buttons because: 

> Apparently, this seems to be the correct URL when you want to include your own custom button and bypass calling pinit.js.

**Comment by billerickson** [comment]
Jared pointed out adding `data-pin-do="none"` resolves this.

**Comment by blogambitions** [comment]
adding data-pin-custom="true" will make it so that Pinterest won't adjust any custom css or html you've added to the button.

this url "https://www.pinterest.com/pin/create/button/" will still work for the button.

data-pin-do determines which image is pinnable. I'd assume that marking none would make it so that no image can be saved to pinterest?

source: https://developers.pinterest.com/docs/widgets/save/

**Comment by blogambitions** [comment]
yeah, testing data-pin-do="none" results in this:

![data-pin-do-none](https://user-images.githubusercontent.com/9809643/40367192-9ffebcb6-5d8d-11e8-9a3f-8d44be0b7f7a.PNG)

**Comment by jaredatch** [comment]
@blogambitions thanks for the details, really appreciate it :)

**Comment by billerickson** [comment]
This change prevented the button from being changed visually, but pinit.js still makes our Pinterest button nonfunctional. It moves the pinterest link from `href` to `data-pin-href`, so when you click the Pinterest button it opens a blank window.

We should check if `data-pin-href` exists, and if so use that URL in our global JS file. It's hacky but seems to be the only solution.
