### ISSUE TITLE
Total has count, but not displaying.

### ISSUE THREAD

**Issue by JiveDig** [jaredatch/Shared-Counts#36]
We moved a site to https from http. HTTPS shows specific counts, HTTP does as well. Total does not, it only shows a total, and front end shows 0's.

## Current Behavior
Share counts showing 0

## Expected Behavior
Counts show correct number.

## Screenshots (if appropriate)
![screen shot 2018-05-10 at 4 46 28 pm](https://user-images.githubusercontent.com/540990/39893483-e0971770-5471-11e8-80c8-3fa3c3b36e7f.png)

![screen shot 2018-05-10 at 4 48 50 pm](https://user-images.githubusercontent.com/540990/39893530-08c8eaca-5472-11e8-85e3-aca6fe3e41c0.png)

Trying to replace Social Warfare permanently. I liked EA Share Counts before, but Shared Counts may finally be my go to. Just trying to wrap up some issues with using it.

**Comment by jaredatch** [comment]
Hmm, that's very strange. My first guess would be caching but I'm sure you tried blowing that away already.

My second guess is maybe one of the APIs is returning an error, which we're not expecting/handling, and it's nuking the data structure/integrity.

I'd check the post_meta keys and see what's turning up in there. Stick something like below in your template (will only show for admins)

```
if ( is_super_admin() ) :
echo '<pre>' . get_post_meta( get_the_ID(), 'shared_counts', true ) . '</pre>';
echo '<pre>' . get_post_meta( get_the_ID(), 'shared_counts_groups', true ) . '</pre>';
endif;
```

**Comment by billerickson** [comment]
@JiveDig Were you able to figure out the issue here?

**Comment by JiveDig** [comment]
Actually I had to move on to another project, but checking back showed the counts eventually updated. Very well could have been cache though I dumped. If I see this again next time I'll swing back. Thanks y'all.
