### ISSUE TITLE
Hide Empty setting not working

### ISSUE THREAD

**Issue by robwoodgate** [jaredatch/Shared-Counts#38]
## Plugin version
1.1.0

## Current Behaviour
The Hide empty setting has no effect on display of share counts

## Expected Behaviour
Buttons with empty counts should not show zero count if Hide Empty setting is ticked.

## Possible Solution
Line 595 of shared-counts/includes/class-shared-counts-front.php uses the identical operator (===) when checking the $link['count'] value.

This is failing because the link count variable type is a string zero, not an integer.

Solutions:

1) Use == instead so comparison is type insensitive:
`if ( 'false' === $show_empty && 0 == $link['count'] ) {`

2) Compare to zero as a string
`if ( 'false' === $show_empty && '0' === $link['count'] ) {`

3) Cast $link['count'] to integer before comparison
`if ( 'false' === $show_empty && 0 === (int)$link['count'] ) {`

**Comment by jaredatch** [comment]
Thanks! 👍 

Fixed in 1.1.2 - I'll try to get it out soon.

https://github.com/jaredatch/Shared-Counts/commit/394347eea2cb06568beb86789792689cbcd175b2
