### ISSUE TITLE
[feature request] Pinterest-specific image

### ISSUE THREAD

**Issue by JiveDig** [jaredatch/Shared-Counts#40]
Just wanted to ask before I built something. A lot of our clients use the SW Pro feature that allows you to upload a specific image for Pinterest. I thought Yoast did this, but it doesn't. I did a little thing with ACF(or CMB, idk) on another site using EA Share Counts. Basically just a custom image field, and filtering the share link to add it.

Just curious if that is something you've thought about? Seems more add-on territory rather than in the core plugin, but wanted to ask anyway.

I'm still looking for way to force Pinterest to use a different image when pasting the raw URL in as well, but not how since it seems to use the og:image which is a different size.

**Comment by JiveDig** [comment]
Yes very much agree. Off by default, then on for posts only with a filter to add support for other post types. If it was made an official add-on, maybe a small setting for post types to use it on but I'm with you that cluttered backend is no fun.

**Comment by jaredatch** [comment]
I'm already doing this for a client, they set specific/special vertical images for Pinterest.

Here's what I've been using

```php
/**
 * Custom Pinterest images for Shared Counts.
 *
 * @param array $link Link attributes.
 * @param int   $id   Post ID or hash ID.
 *
 * @return array
 */
function ja_shared_counts_pinterest_image( $link, $id ) {

	if ( 'pinterest' === $link['type'] ) {
		$pin_image = get_post_meta( $id, '_pinterest_image', true );
		if ( ! empty( pin_image ) ) {
			$link['link'] = sprintf( 
				'https://pinterest.com/pin/create/button/?url=%s&media=%s&description=%s',
				esc_url_raw( $link['url'] ),
				esc_url_raw( $pin_image ),
				sanitize_text_field( $link['title'] )
			);
		}
	}

	return $link;
}
add_filter( 'shared_counts_link', 'ja_shared_counts_pinterest_image', 10, 2 );

In general my thoughts on things like this, that don't necessarily apply to "most" users, is to make it into a small addon plugin, which we link to in the GH and .org profiles. If some of the addons end up gaining traction/popularity, then we can consider merging them into core.
```

**Comment by billerickson** [comment]
Yeah that's the easy part. The harder part is building the metabox that provides the image upload field.

Cool, lets go with an add-on plugin.

**Comment by JiveDig** [comment]
@jaredatch Assuming you are just using Carbon/ACF/CMB for the field as well? Image fields from scratch have def deterred me from some fully custom stuff as well.

**Comment by jaredatch** [comment]
I do sometimes use those (I tend to jump them depending on the project and what was inhereted).

But with that said, image from scratch field is actually much easier than it appears or you would think.

Check out the generalized example below (taken from WPForms 😁). This uses the media modal to upload/select the image, then returns the image URL into your custom input field. Would be perfect for something like that.


```js

;(function($) {

	var media_modal = false;

	/**
	 * Bind upload/select image button.
	 */
	$( document ).on( 'click', '.myplugin-setting-row-image button', function( event ) {

		event.preventDefault();

		imageUploadModal( $( this ) );
	});


	/**
	 * Image upload modal window.
	 */
	imageUploadModal: function( el ) {

		 if ( media_modal ) {
			 media_modal.open();
			 return;
		 }

		 var $setting = $( el ).closest( '.myplugin-setting-row' );

		 media_modal = wp.media.frames.wpforms_media_frame = wp.media({
			 className: 'media-frame wpforms-media-frame',
			 frame: 'select',
			 multiple: false,
			 title: 'Upload or Choose Your Image',
			 library: {
				 type: 'image'
			 },
			 button: {
				 text: 'Use Image'
			 }
		 });

		 media_modal.on( 'select', function(){
			 // Grab our attachment selection and construct a JSON representation of the model.
			 var media_attachment = media_modal.state().get( 'selection' ).first().toJSON();

			 // Send the attachment URL to our custom input field via jQuery.
			 $setting.find( 'input[type=text]' ).val( media_attachment.url );
			 $setting.find( 'img' ).remove();
			 $setting.prepend( '<img src="'+media_attachment.url+'">' );
		 });

		 // Now that everything has been set, let's open up the frame.
		 media_modal.open();
	},

})( jQuery );
```

```html
<!-- make sure this page has wp_enqueue_media() -->
<div class="myplugin-setting-row myplugin-setting-row-image">
	<span class="myplugin-setting-label">
		<label>Header Image</label>
	</span>
	<span class="myplugin-setting-field">
		<img src="">
		<input type="text" name="something" value="">
		<button class="myplugin-btn myplugin-btn-md myplugin-btn-light-grey">Upload Image</button>
	</span>
</div>
```

**Comment by billerickson** [comment]
Add on plugin now built! [Shared Counts - Pinterest Image](https://github.com/billerickson/Shared-Counts-Pinterest-Image/blob/master/README.md)

Let me know how it works for you. You'll need to pull down the `develop` branch of Shared Counts because I had to make some changes (see above commits)

**Comment by jaredatch** [comment]
To-do to close this ticket:

- [ ] Create "Addons" wiki page, with this as the first item. Make sure and indicate this is an official addon in some way (not 3rd party) in case we want to list 3rd party addons in the future.

- [ ] Update README.md (GH)

- [ ] Update readme.txt (.org)

**Comment by JiveDig** [comment]
Rock on. This looks great!
