### ISSUE TITLE
Don't display "Included Total" button if 0 shares and "hide empty counts" is true

### ISSUE THREAD

**Issue by billerickson** [jaredatch/Shared-Counts#44]
We currently display the "Included Total" button whether or not there are any shares. If "Hide Empty Counts" is checked, the 0 is removed but the button itself stays, so it just says "Shares".

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/3k290j2W3N2P3u2A0V0d/Screen%20Shot%202018-05-25%20at%201.36.45%20PM.png?X-CloudApp-Visitor-Id=62fe8f264d77e04f553532f39036a9d7&v=8265eb86)

This makes sense in the context of the other buttons (the FB share button should appear regardless of the share count), but not so with this button.

I think we should remove the "Included Total" button entirely if "hide empty counts" is true and the share count is zero.

---

Until this is patched and publicly released, you can implement this on your own site by adding the following to your theme's functions.php file or a [core functionality plugin](https://www.billerickson.net/core-functionality-plugin/).

```php
/**
 * Shared Counts, don't display total if 0 counts
 *
 */
function be_shared_counts_remove_empty_total( $element, $link ) {
	if( 'included_total' == $link['type'] && empty( $link['count'] ) ) {
		$element['wrap_open'] = $element['icon_label'] = $element['icon_count'] = $element['wrap_close'] = '';
	}
	return $element;
}
add_filter( 'shared_counts_output_elements', 'be_shared_counts_remove_empty_total', 10, 2 );
```

**Comment by JiveDig** [comment]
Just chiming in to say I tested develop just now and it fixed this issue for me as well 👍
