### ISSUE TITLE
If settings page is not saved, no style is used on frontend

### ISSUE THREAD

**Issue by billerickson** [jaredatch/Shared-Counts#47]
This isn't a common issue since most people use the settings page to add the share buttons to the page, but if your theme or plugin already has Shared Counts support, you'll get unstyled buttons.

Steps to reproduce:

1. Install and activate the Shared Counts plugin
2. In a theme or plugin, display it using `ea_share()->front->display()`

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/412I132f1P1k1I0u0q21/Screen%20Shot%202018-05-31%20at%203.29.31%20PM.png?X-CloudApp-Visitor-Id=62fe8f264d77e04f553532f39036a9d7&v=f4f1a222)

![another](https://d3vv6lp55qjaqc.cloudfront.net/items/2X0s14143O0O381Y2K0S/Screen%20Shot%202018-05-31%20at%203.31.04%20PM.png?X-CloudApp-Visitor-Id=62fe8f264d77e04f553532f39036a9d7&v=a8947880)

**Comment by jaredatch** [comment]
I think we just need to set a default style.

https://github.com/jaredatch/Shared-Counts/blob/develop/includes/class-shared-counts-admin.php#L598
