### ISSUE TITLE
Share buttons not showing correctly - new install

### ISSUE THREAD

**Issue by trailguideweb** [jaredatch/Shared-Counts#53]
Version 1.2.0

## Current Behavior
1) The plugin is set to Classic view and not displaying as expected. Looks like a CSS issue? 
2) Tested other sharing plugins and the buttons display correctly
3) Deactivated installed plugins to test for conflict - did not help

![social-count-share-buttons](https://user-images.githubusercontent.com/40649173/42009291-8a2f9dba-7a3e-11e8-9db7-cc24f7a375c0.jpg)

**Comment by billerickson** [comment]
It looks like your theme is overriding the styles for the button. Can you provide a link to the page?

You'll likely need to modify your theme to add more specific CSS styling.

**Comment by trailguideweb** [comment]
Thanks Bill! That would be awesome - here is a link: http://laurabonarrigo.com/articles-1/2018/05/31/loneliness-is-the-new-badge-of-honor/

**Comment by billerickson** [comment]
Add this to your theme's stylesheet, or in Appearance > Customize > Custom CSS:

```.shared-counts-wrap .shared-counts-button { letter-spacing: normal; }```

**Comment by trailguideweb** [comment]
Thank you!! That worked perfectly.
