### ISSUE TITLE
New 3rd-party Twitter API support

### ISSUE THREAD

**Issue by jaredatch** [jaredatch/Shared-Counts#62]
NewSharedCounts is dead. RIP.

Now it's on to the next one 🙄 

Two contenders are:
- opensharecount.com
- twitcount.com

We need to research them, see what the pro's and con's are, then move forward with integrating one in place of NewSharedCounts. The actual swap should be pretty simple if it's anything like NSC.

Upon quick glance, opensharecount.com only allows tracking 1 domain per Twitter user account which is a bummer, can't tell if twitcount.com has a similar restriction or not.

**Comment by yorksy1** [comment]
Hello,

I just wondered if there has been any progress with this issue?

Thanks!

**Comment by billerickson** [comment]
Social Pug uses TwitCount for its twitter counts: http://docs.devpups.com/social-pug/how-to-activate-twitter-tweet-counts/

**Comment by jaredatch** [comment]
Twitcount was added thanks to a PR.

See https://github.com/jaredatch/Shared-Counts/commit/bc41c6a7f6c024b09a1e4f8143ec1501eb47d867
