### ISSUE TITLE
Pinterest icon throws a HTML validation error

### ISSUE THREAD

**Issue by oldrup** [jaredatch/Shared-Counts#64]
Site still works though...

Error given:

Error: Bad value for attribute href on element a: Illegal character in query: space is not allowed.

![image](https://user-images.githubusercontent.com/17141205/43288110-391d979c-9127-11e8-88de-3ac29c99974e.png)

- Bjarne

**Comment by jaredatch** [comment]
Fixed in next release, see https://github.com/jaredatch/Shared-Counts/commit/58cbfd5920215fc55caee0553c0a9f195fa8885f
