### ISSUE TITLE
About:Blank Pinterest Button

### ISSUE THREAD

**Issue by jenniferquisenberry** [jaredatch/Shared-Counts#66]
## Current Behavior
I'm using both the Shared Counts and Shared Counts - Pinterest Image on my site, https://.www.champagneandcoconuts.com. Both my WP and Genesis are up to date. 

My sharing button for Pinterest is not working. When I mouse over it, it says Share to Pinterest, but when I click it, rather than always opening a pin url, it instead opens "about:blank" in a popup window. 

I have deactivated / reactivated the plugin with the same results. 

I have tested this in Chrome, Edge, and Firefox. On both Chrome and Firefox, the url bar said "about:blank". On Edge, it simply opened up a blank window and the page title was "blank page."

## Expected Behavior
What should happen when I click on the Pinterest share button is that my pinnable image should appear along with a list of my pin boards where I can save the image.

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
1. https://www.champagneandcoconuts.com/sparkling-wine-makes-boozy-black-cherry-float-bomb/
2. Note that it is doing this on all of my posts, not just the one aforementioned.
3. Mouse over Pinterest button. No url will appear at the bottom left of the screen. Note that the other share buttons are working.
4. Click Pinterest button. You will see that it usually opens a blank popup window without a url. Instead of an url, it states, "about:blank".
5. When it does populate with a pin to save, it is pulling the featured image rather than the image I saved via Pinterest Sharing Image.
![pinterest button issue git hub 8 11 18](https://user-images.githubusercontent.com/42306497/43997158-1c118f00-9d89-11e8-812f-2beb75b197ed.JPG)

## Screenshots (if appropriate)
1 attached

**Comment by billerickson** [comment]
Are you sure it's not an ad blocker or issue with your specific browser? Have you tried it in different browsers on your computer?

I just tested it on your site and it worked fine for me. Here's a video: https://cl.ly/1V2t1C0M3O42

**Comment by dlangham** [comment]
I can reproduce the bug by clicking inside the smaller elements (`span`, `span`, and `svg`) within the main `a` tag. Conversely, if I click inside the `a` tag but outside its smaller inner elements, the button works correctly.

I tried this with ad-blocker on and off: same results.

(Also, there is no hover `cursor: pointer;` taking effect for Pinterest, though it does for the others.)

**Comment by jaredatch** [comment]
The issue is that the official Pinterest JS hijacks most/all Pinterest links/buttons on the page.

As a side affect, that breaks our button as well. A bit more on that is discussed in #34.

We didn't catch the issue originally because both Bill and myself use ad blockers, which block the Pinterest JS, which causes the popup to work as expected since it prevents the conflict 😆 

We're planning a fix for it in our next update, but no ETA on that quite yet. Removing the Pinterest JS from loading in the page will obviously resolve the issue as well.

**Comment by dlangham** [comment]
For reference, the ad blocker I'm using is uBlock Origin on Chrome, and the bug does occur for me, as described above. Turning it on or off doesn't change the button's behavior (yes I refreshed the page).

**Comment by billerickson** [comment]
As Jared described, it isn't the ad blocker causing the issue but the **Pinterest JS code** you've added to your page. It hijacks any links to Pinterest.

**Comment by dlangham** [comment]
> both Bill and myself use ad blockers, which block the Pinterest JS, which causes the popup to work as expected since it prevents the conflict

Yes, I understand. I only mentioned it for future reference in case it's needed, since Jared says here that the ad blocker causes the popup to work correctly for you both (by blocking the Pinterest JS code), but ad blocker doesn't cause it to work correctly in my case.

**Comment by jenniferquisenberry** [comment]
I'm not using an Ad Blocker on my computer, and I tested it on Chrome, Firefox and Edge prior to opening the issue. It was discovered by one of my readers who wanted to pin the recipe.

I'm not a developer, so please forgive the layman's speak. If I were to remove the Pinterest JS, is that the code that I add to the footer of my page when I want to embed a pin board widget? Or is that related to using Rich Pins? 

The interactions with Pinterest on my site are: Rich Pins have been enabled and verified via meta tag (and I need rich pins functionality), I have the Tasty Pins plugin, I have used the embed board widget code on a handful of posts,  Is one of these the Pinterest JS causing the problem? If so, is there something I can do in the meantime? I love this plugin; it's so light and doesn't slow down my site, so I'd love to make a tweak to make it work until the next update.

Thanks!

**Comment by jaredatch** [comment]
Closed, see #34
