### ISSUE TITLE
Fix for Email counts not working

### ISSUE THREAD

**Issue by thartl** [jaredatch/Shared-Counts#67]
Email counts were not incrementing for me and a couple small code edits made it work.
I thought I'd share in case this is a valid fix.  I will fork and submit a pull request.

## Current Behavior
With the plugin set to use SharedCount.com as Count Source, email shares were not incrementing.

## Possible Solution
In class-shared-counts-core.php:
1) On Line 125, changed the comparison operator from === to !==
2) On Line 127, changed post-increment ($count++) to pre-increment (++$count)

**Comment by jaredatch** [comment]
@thartl much appreciated :)

**Comment by thartl** [comment]
My pleasure. Thank you for a great plugin.
