### ISSUE TITLE
Fancy implementation: Facebook count not showing up

### ISSUE THREAD

**Issue by samruiz** [jaredatch/Shared-Counts#72]
## Plugin version
Version 1.2.0 
## Current Behavior
This post has several engagements in FB, but not showing in the article post: 
https://www.danvillesocial.com/danville-news/danville-found-to-be-the-safest-city-in-california/

## Expected Behavior
Expecting to see a count next to FB based on the stats of the post: 
https://screencast.com/t/ROEyg9Se81J

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Screenshots (if appropriate)
https://screencast.com/t/ROEyg9Se81J

**Comment by jaredatch** [comment]
Check the Shared Counts plugin settings and confirm you have counts enabled to display. That style I believe might be designed to be used with the "Total" share count box which isn't currently configured in the settings to display. Adding that should resolve the issue :)

In the backend everything seems to be working properly https://cl.ly/c4ea012d4a73
