### ISSUE TITLE
Update Facebook button primary color

### ISSUE THREAD

**Issue by jaredatch** [jaredatch/Shared-Counts#79]
Facebook is in the middle of a rebrand.

See https://www.newscaststudio.com/2019/05/01/new-facebook-logo/

Once the rebrand is complete we'll need to push an update that adjusts the button to use the new blue color.

When this is done, it would be a good time to update the screenshots and banner images, since some of the buttons currently displayed are removed in version 1.3.

**Comment by billerickson** [comment]
It's been 4 months and Facebook is still using the old blue color. I'm closing this for now and we can re-open when the official buttons are updated.
