### ISSUE TITLE
Regain shares after URL changes

### ISSUE THREAD

**Issue by normski232** [jaredatch/Shared-Counts#85]
Hello

I have a question before installing the plug in.
Recently I redirected pages from wesbite1.com/post1 etc to website2.com/post1 etc
Is it possible to carry the shares over from the posts on website1.com to website2? 
Website1 and website2 are both active.
Many thanks.

**Comment by billerickson** [comment]
Yes, when editing a post you can use the Shared Counts metabox in the right column to add additional URLs to pull for the current page/post. 

You could manually go through and add each post's previous URL, or if you're comfortable with code you can programmatically update all posts. Add one URL manually, look at the post metadata (how Shared Counts saves the data), then update the post meta on all posts using the same syntax.
