### ISSUE TITLE
HOOOOOOW!?!?!?!

### ISSUE THREAD

**Issue by blaasvaer** [jaredatch/Shared-Counts#86]
Well, I may be completely stupid. But, I've installed this plugin, read through the plugin support page, read the documentation ... and NOWHERE can I find a simple example of HOW to actually make it show up in my posts!?

Now, HOW can essential information like this 'disappear' in all that 'communication', I'm really curious to find out. I seriously hope that I simply overlooked something – and IF that's the case, then please EMPHASIZE it ... otherwise please ADD IT WHERE IT BELONGS, namely in the description on the plugin page. Thanks.

And yes, I've set the Theme Location to None, as I'd expect to be able to decide myself where to put this ...

```
[shared_counts]
```
is NOT working.

**Comment by billerickson** [comment]
In Settings > Shared Counts you can select where the share buttons can appear automatically (Before Content, After Content, Before & After Content).

Alternatively, you can use the `[shared_counts]` shortcode to manually display them.

If the shortcode is not working, it is likely an issue with your theme or a plugin conflict. You can use the [Health Check](https://wordpress.org/plugins/health-check/) plugin to troubleshoot the issue ([more information](https://displayposts.com/2019/04/20/using-health-check-plugin-to-find-theme-and-plugin-conflicts/)).

Where are you adding the shortcode? In the content area of a post/page, or into a widget area? What do you see? Do you see the `[shared_counts]` shortcode text on the frontend or nothing?

If you see the shortcode text rendered on the frontend, that means your theme is not configured to render shortcodes wherever you are typing it.

**Comment by blaasvaer** [comment]
Well, nevermind. I wrote my own plugin. Way faster … thanks.
