### ISSUE TITLE
Total Shared Count not working.

### ISSUE THREAD

**Issue by deftruler** [jaredatch/Shared-Counts#93]
Hello,

Using the share counts plugin on my site but total shares are not showing.

One of my page for facebook shares  [https://www.deftruler.com/edureka-coupon-codes/](https://www.deftruler.com/edureka-coupon-codes/)

Please help us.

**Comment by foysalremon** [comment]
Same here. I have tried all the options. It seems it will not work anymore, or till update.

**Comment by richardmorse441** [comment]
Same here. In the Admin bar and Dashboard Widget, it's showing 911 (Total Shares Count) but it's not showing the same where I am displaying the social buttons. 

Post URL: https://insidebedroom.com/sleeping-positions/
![image](https://user-images.githubusercontent.com/25720305/93663023-40518c00-fa82-11ea-9ac0-2a99ba68488c.png)

Note: I have selected an option - Hide Zero Count.

**Comment by billerickson** [comment]
Have you tried adding the "Total Counts" field in the "Share Buttons to Display"?

Do you have "Count Total Only" selected? If so, it will not include the counts on the individual button, and only the "Total Counts" button will include a count. Looking at the code of your buttons I see they have a class of "shared-counts-no-counts" , which only gets added if "Count Total Only" is selected or the current service has no shares.

**Comment by richardmorse441** [comment]
Hello @billerickson 

> Have you tried adding the "Total Counts" field in the "Share Buttons to Display"?

Yes. Please check the screenshot. 
![image](https://user-images.githubusercontent.com/25720305/93668267-efa15980-faa8-11ea-8c1e-aa2df3754973.png)

> Do you have "Count Total Only" selected? If so, it will not include the counts on the individual button, and only the "Total Counts" button will include a count. 

Yes, I want to show Total Count only not individual count on each button. 

As you can see in the admin bar (please refer screenshot from the first comment) total count for [this post](https://insidebedroom.com/sleeping-positions/) is 911 but it's not displaying. I checked a couple of other posts, it's working for other posts but not for this one :( 

Am I missing something here? Please advise.

Thanks in advance.

**Comment by billerickson** [comment]
I wasn't able to replicate this issue today while preparing the next plugin release. Since the ticket is 4 years old, I'm closing for now. If you still have this issue, please create a new issue.
