### ISSUE TITLE
Pinterest Image

### ISSUE THREAD

**Issue by joecancook** [jaredatch/Shared-Counts#97]
The Pinterest image and description section are not displaying on Pinterest.

## Plugin version
1.2.0
## Current Behavior

I have updated posts with the new Pinterest Image and Description section and the image is not updated on Pinterest. 

I have also created new posts, entered in the Pinterest Image and Description on the post and when it posts to Pinterest, it is not displaying the preferred Pinterest Image and Description.

## Expected Behavior

The plugin should force the requested Pinterest Image and Description to display on Pinterest.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by billerickson** [comment]
Can you provide a link to a specific post that has the issue?

The [Shared Counts - Pinterest Image](https://wordpress.org/plugins/shared-counts-pinterest-image/) extension only applies when a visitor clicks the Shared Counts pinterest button. If they pin the image by other means (browser extension, another plugin on your site, repinning something already on Pinterest) it will have no effect.

**Comment by joecancook** [comment]
Hi Bill,

Here is one post. https://joeeatsworld.com/test-kitchen/sourdough-bread-starter-for-beginners/ <https://joeeatsworld.com/test-kitchen/sourdough-bread-starter-for-beginners/>

I guess I misunderstood the plugin then. I thought the Pinterest Image plugin posted the image I chose when I published my post. 

Thanks,

	
Joe Morales
Chef/Traveler/Writer
w:	www.joeeatsworld.com <http://www.joeeatsworld.com/>  e: joe@joeeatsworld.com <mailto:joe@joeeatsworld.com>
 <https://facebook.com/joeeatsworld>   <https://twitter.com/joeeatsworld>   <https://instagram.com/joeeatsworld1>

**Comment by billerickson** [comment]
If you click the "Pin" button on that post, it will use this image:

![screenshot](https://joeeatsworld.com/wp-content/uploads/2020/04/freshly-baked-sourdough-bread.jpg)

And this description: Fresh baked sourdough bread sitting on a white cloth napkin #baked #sourdough #bread

Is that what you have set in the plugin?

**Comment by joecancook** [comment]
Perfect. Ok. Yes. That’s what I have. I thought it was something automatic that would post when I published my post.

Thank you,


	
Joe Morales
Chef/Traveler/Writer
w:	www.joeeatsworld.com <http://www.joeeatsworld.com/>  e: joe@joeeatsworld.com <mailto:joe@joeeatsworld.com>
 <https://facebook.com/joeeatsworld>   <https://twitter.com/joeeatsworld>   <https://instagram.com/joeeatsworld1>
